### ISSUE TITLE
Entity graphics example is broken

### ISSUE THREAD

**Issue by dimagoldin** [darwin-education/resium#346]
https://resium.darwineducation.com/examples/?path=/story/entity--graphics

Shows the following error:
```
An error occurred while rendering. Rendering has stopped.
DataCloneError: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already detached.
Error: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already detached.
    at https://resium.darwineducation.com/cesium/Cesium.js:23:260609
    at Promise$1.then (https://resium.darwineducation.com/cesium/Cesium.js:23:79376)
    at when (https://resium.darwineducation.com/cesium/Cesium.js:23:79019)
    at TaskProcessor.scheduleTask (https://resium.darwineducation.com/cesium/Cesium.js:23:260441)
    at loadAsynchronous (https://resium.darwineducation.com/cesium/Cesium.js:23:1033783)
    at Primitive.update (https://resium.darwineducation.com/cesium/Cesium.js:23:1047123)
    at PrimitiveCollection.update (https://resium.darwineducation.com/cesium/Cesium.js:23:1509813)
    at PrimitiveCollection.update (https://resium.darwineducation.com/cesium/Cesium.js:23:1509813)
    at PrimitiveCollection.update (https://resium.darwineducation.com/cesium/Cesium.js:23:1509813)
    at updateAndRenderPrimitives (https://resium.darwineducation.com/cesium/Cesium.js:23:3015303)
```

Any working example i could see?

**Comment by rot1024** [comment]
I confirmed that I can see the page with no problem. The error seems due to your browser or environment.

![image](https://user-images.githubusercontent.com/3888696/80708381-884d3200-8b26-11ea-82ed-49eeea94b4ad.png)
