### ISSUE TITLE
at GeoJsonDataSource.stories.tsx,throw error"describe is not defined"

### ISSUE THREAD

**Issue by windcatcher** [darwin-education/resium#48]
at GeoJsonDataSource.stories.tsx,throw error"describe is not defined"

describe is not defined
    ReferenceError: describe is not defined
    at load (http://localhost:9001/main.6bf02358e258f58db97d.bundle.js:1343:19)
    at Object.mount (http://localhost:9001/main.6bf02358e258f58db97d.bundle.js:1372:17)
    at CesiumComponent.mount (http://localhost:9001/main.6bf02358e258f58db97d.bundle.js:3894:22)
    at CesiumComponent.componentDidMount (http://localhost:9001/main.6bf02358e258f58db97d.bundle.js:3836:18)
    at commitLifeCycles (http://localhost:9001/vendors~main.6bf02358e258f58db97d.bundle.js:48252:22)
at commitAllLifeCycles (http://localhost:9001/vendors~main.6bf02358e258f58db97d.bundle.js:49617:7)
    at HTMLUnknownElement.callCallback (http://localhost:9001/vendors~main.6bf02358e258f58db97d.bundle.js:32174:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9001/vendors~main.6bf02358e258f58db97d.bundle.js:32224:16)
    at invokeGuardedCallback (http://localhost:9001/vendors~main.6bf02358e258f58db97d.bundle.js:32281:31)
    at commitRoot (http://localhost:9001/vendors~main.6bf02358e258f58db97d.bundle.js:49813:7)

**Comment by rot1024** [comment]
Thank you for reporting the error! This is my mistake. I'll fix it soon.
